num_epochs: 3000
dataset_name: "antmaze-medium-diverse-v2"

eval_every: 500
eval_episodes: 100
gamma: 0.999

drnd_update_epochs: 100
drnd_switch_features: true
drnd_mlp_type: "torch_bilinear_first"
drnd_target_mlp_type: "film_last"
normalize_reward: true

