num_epochs: 3000
dataset_name: "walker2d-medium-v2"

drnd_update_epochs: 100
drnd_switch_features: true
drnd_mlp_type: "torch_bilinear_first"
drnd_target_mlp_type: "film_last"

batch_size: 1024
critic_learning_rate: 0.001
actor_learning_rate: 0.001
alpha_learning_rate: 0.001